export const GET_CATEGORY_LIST = "GET_CATEGORY_LIST";
export const GET_CATEGORY_LIST_SUCCESS = "GET_CATEGORY_LIST_SUCCESS";
export const GET_CATEGORY_LIST_FAIL = "GET_CATEGORY_LIST_FAIL";

export const GET_SEARCH_LIST = "GET_SEARCH_LIST";
export const GET_SEARCH_LIST_SUCCESS = "GET_SEARCH_LIST_SUCCESS";
export const GET_SEARCH_LIST_FAIL = "GET_SEARCH_LIST_FAIL";

export const API_KEY = "pJGDxNjVKpPRmSyBwH7ffj1qLpMXDuth";
